export const portfolioData = {
  header: {
    logo: "VP.",
    navLinks: [
      { name: "About", url: "#about" },
      { name: "Skills", url: "#skills" },
      { name: "Experience", url: "#experience" },
      { name: "Projects", url: "#projects" },
      { name: "Contact", url: "#contact" },
    ],
  },
  hero: {
    greeting: "Hi, I'm",
    name: "Vaibhav Patel",
    roles: ["Backend Developer", "Full Stack Developer", "Cloud Engineer"],
    tagline: "I build scalable systems and ship products that matter.",
    description:
      "Full Stack Engineer with 3+ years of experience building and operating scalable distributed systems in production environments. Specializes in AWS serverless architectures and owning complex features end-to-end.",
    cta1: "View My Work",
    cta2: "Get In Touch",
    status: "Open to opportunities",
  },
  about: {
    name: "Vaibhav Patel",
    bio: "I'm a Full Stack Engineer and Cloud Engineer based in Canada, specializing in building robust applications and scalable cloud infrastructure. I care deeply about developer experience, system performance, and writing software that stands the test of time.",
    bio2: "When I'm not shipping features, I'm building side projects, leading community events, or exploring new technologies. Currently working at Air Canada via TCS as a Backend Developer while actively building Insights, a personal finance platform powered by AI.",
    cvLink: "/VaibhavPatel-Resume.pdf",
    location: "Toronto, Canada",
    availability: "Open to opportunities",
    stats: [
      { value: "3+", label: "Years Experience" },
      { value: "5", label: "Companies" },
      { value: "5+", label: "Projects Shipped" },
      { value: "800+", label: "Payments Processed" },
    ],
  },
  skills: {
    languages: [
      { name: "TypeScript" },
      { name: "JavaScript" },
      { name: "Python" },
      { name: "Go" },
      { name: "Java" },
      { name: "SQL" },
      { name: "HTML/CSS" },
    ],
    frameworks: [
      { name: "React" },
      { name: "Next.js" },
      { name: "Node.js" },
      { name: "Express" },
      { name: "Redux Toolkit" },
      { name: "Tailwind CSS" },
      { name: "Laravel" },
      { name: "Flask" },
      { name: "React Native" },
      { name: "Three.js" },
      { name: "Stripe" },
    ],
    databases: [
      { name: "PostgreSQL" },
      { name: "MongoDB" },
      { name: "Firebase" },
      { name: "Firestore" },
      { name: "Redis" },
      { name: "MySQL" },
      { name: "MS SQL" },
    ],
    devops: [
      { name: "AWS" },
      { name: "Azure" },
      { name: "Google Cloud" },
      { name: "Docker" },
      { name: "Terraform" },
      { name: "GitHub Actions" },
      { name: "CI/CD" },
      { name: "Nginx" },
      { name: "Linux" },
    ],
  },
  experience: [
    {
      id: 1,
      role: "Backend Developer",
      company: "Air Canada",
      companyNote: "via TCS",
      type: "Full-time",
      location: "Remote",
      duration: "June 2025 - Present",
      current: true,
      description: [
        "Architected and owned the Disruption Resolution Engine, handling flight disruptions (cancellations, cabin changes, time/flight changes, operational delays) for itinerary reconciliation in mission-critical systems.",
        "Redesigned system by separating regular and disruption flows, eliminating circular dependencies and enabling rapid feature addition. Currently handling 50% of production traffic.",
        "Engineered BFS-based graph traversal algorithm to correctly match disrupted segments across complex PNR types (one-way, round-trip, multi-city). Proactively caught critical edge case in operational delay handling that would have silently skipped segments.",
        "Optimized performance through intelligent DynamoDB caching, eliminating redundant EIP calls and expensive graph calculations for repeated PNRs.",
        "Coordinated cross-team integration of meal preorder feature across timezones, implementing graceful error handling and driving operational excellence through Dynatrace and Splunk observability.",
      ],
      highlights: [
        "50% of production traffic",
        "BFS disruption matching algorithm",
        "DynamoDB caching optimization",
      ],
    },
    {
      id: 2,
      role: "Full Stack Developer",
      company: "Wiltekk Digital Solutions",
      companyNote: "",
      type: "Remote",
      location: "Remote",
      duration: "Mar. 2024 - Jun. 2025",
      current: false,
      description: [
        "Developed web applications with Laravel MVC architecture, ORM, and blade templating for efficient, scalable delivery.",
        "Set up a staging environment on AWS to reduce deployment risks, enabling full API and CMS testing before production.",
        "Configured Nginx on EC2 instances to optimize backend-to-frontend communication and application responsiveness.",
        "Built CI/CD pipelines with GitHub Actions, cutting deployment time by 40% and reducing production incidents.",
        "Resolved 35 reported issues in Android Studio and identified API performance bottlenecks in AWS Lambda, achieving 10% improvements.",
      ],
      highlights: [
        "40% reduction in deployment time",
        "10% API performance improvement",
      ],
    },
    {
      id: 3,
      role: "Cloud Engineer",
      company: "Manulife",
      companyNote: "Co-op",
      type: "Full-time",
      location: "Toronto, ON",
      duration: "Sep. 2023 - Dec. 2023",
      current: false,
      description: [
        "Reduced subscription costs by automating cleanup of expired Azure resources using Python scripts, Azure Automation, and Azure Resource Graph.",
        "Automated Azure resource provisioning via Terraform, reducing deployment time by 10% and improving scalability.",
        "Participated in code reviews to maintain code quality and enforce team best practices.",
      ],
      highlights: ["10% faster deployments", "Automated cloud cost reduction"],
    },
    {
      id: 4,
      role: "Software Developer",
      company: "Gravioty Research",
      companyNote: "Part-time",
      type: "Remote",
      location: "Remote",
      duration: "Jan. 2023 - Aug. 2023",
      current: false,
      description: [
        "Built a multi-currency crypto wallet from scratch supporting Ethereum and Bitcoin using React, Web3.js, Ethers.js, and Bitcoinjs-lib.",
        "Architected a Redux state management system for optimized wallet data handling and consistency.",
        "Integrated WebSocket for real-time cryptocurrency price feeds across all supported assets.",
        "Improved cross-browser compatibility with dynamic, configurable Webpack scripts.",
      ],
      highlights: [
        "Full crypto wallet from scratch",
        "Real-time WebSocket price feeds",
      ],
    },
    {
      id: 5,
      role: "Software Developer Intern",
      company: "JANA Corporation",
      companyNote: "",
      type: "Full-time",
      location: "Aurora, ON",
      duration: "Mar. 2022 - Aug. 2022",
      current: false,
      description: [
        "Automated QA processes using Python, Pandas, and pyodbc, reducing testing time by 20% across 21 risk models.",
        "Streamlined MS SQL data extraction using Export Wizard and custom queries for efficient risk model input.",
        "Optimized 2 COF risk models by 10% by eliminating redundant calculations in Azure Functions.",
      ],
      highlights: [
        "20% reduction in QA time",
        "10% optimization on risk models",
      ],
    },
  ],
  projects: [
    {
      id: 1,
      title: "Insights",
      subtitle: "Personal Finance Platform",
      summary:
        "A production-grade personal finance platform with a GPT-4 streaming chat assistant, automated Gmail transaction ingestion, AI-powered merchant categorization using OpenAI embeddings, and real-time investment price feeds. Built as a TypeScript monorepo on Firebase, PostgreSQL, and Redis.",
      description:
        "The backend is a Firebase Cloud Functions v2 Express API backed by PostgreSQL and Redis, paired with a React 19 frontend using Redux Toolkit and DaisyUI. The GPT-4 chat assistant supports 14 function-calling tools for reading and writing budgets, transactions, goals, net worth, and portfolio data in real time via SSE streaming. A scheduled Gmail ingestion pipeline runs every 5 hours, parsing 7 bank email types (credit authorizations, Interac transfers, e-statements) and auto-creating transactions. Merchant categorization uses OpenAI text-embedding-3-small embeddings stored in pgvector with cosine similarity lookups, where user-saved preferences take priority at confidence 1.0. Scheduled Firebase jobs handle recurring transactions, loan payments, daily net-worth snapshots, and stock/ETF/metals/FX price feeds cached in Redis every 10 minutes during market hours. The project includes route-level code splitting, 3 PostgreSQL triggers, and 160+ unit tests.",
      techStack: [
        "React 19",
        "TypeScript",
        "Firebase Functions v2",
        "PostgreSQL",
        "Redis",
        "OpenAI API",
        "Gmail API",
        "Redux Toolkit",
      ],
      link: "https://insights.vaibhav.ca",
      github: null,
      featured: true,
      accentColor: "#F59E0B",
    },
    {
      id: 2,
      title: "GoSocial",
      subtitle: "Social API Backend",
      summary:
        "A production-ready REST API for a social platform in Go with 50% faster responses thanks to Redis caching, auto-generated Swagger docs, and CI/CD to Google Cloud Run on every push.",
      description:
        "A production-ready REST API for a social platform built in Go. Reduced API response times by 50% with Redis in-memory caching. Automated Swagger documentation generation for faster developer onboarding. CI/CD via Google Cloud Run triggered on Git push.",
      techStack: [
        "Go",
        "PostgreSQL",
        "Docker",
        "Redis",
        "Swagger",
        "Google Cloud Run",
      ],
      link: null,
      github: "https://github.com/vp2305/GoSocial",
      featured: false,
      accentColor: "#3B82F6",
    },
    {
      id: 3,
      title: "OGSA Platform",
      subtitle: "Event & Ticketing Platform",
      summary:
        "Full-stack event and ticketing platform for 500+ users with RBAC, early-bird ticketing, and Stripe payments via Firebase Cloud Functions, processing 800+ transactions.",
      description:
        "A full-stack event management and ticketing platform for 500+ users. Implemented RBAC with Firebase, a ticketing system with early-bird support, and Stripe plus Firebase Cloud Functions for secure payments, processing 800+ transactions.",
      techStack: ["React", "Firebase", "Stripe", "GCP", "JavaScript"],
      link: null,
      github: null,
      featured: false,
      accentColor: "#A855F7",
    },
    {
      id: 4,
      title: "Vikky",
      subtitle: "Voice-Activated Dev Assistant",
      summary:
        "A Raspberry Pi dev assistant that responds to voice commands in under 600ms. The TTS subsystem was rewritten from scratch with numpy and onnxruntime to run on constrained hardware.",
      description:
        "A Raspberry Pi-based physical dev assistant that responds to voice commands in under 600ms. Rewrote the TTS subsystem from scratch using numpy, onnxruntime, and sounddevice to run on constrained hardware. Integrates with workspace tools via Ollama.",
      techStack: ["Python", "Flask", "Ollama", "Docker", "Raspberry Pi"],
      link: null,
      github: "https://github.com/vp2305/Vikky",
      featured: false,
      accentColor: "#10B981",
    },
    {
      id: 5,
      title: "RideX",
      subtitle: "Ride-Sharing Android App",
      summary:
        "Android ride-sharing app with real-time in-app messaging between drivers and riders, ride posting workflows, and offline-first data persistence via MongoDB and Realm.",
      description:
        "An Android ride-sharing app with MongoDB authentication, real-time in-app messaging between drivers and riders, and ride posting/confirmation workflows. Built with Java and Realm for offline-first data persistence.",
      techStack: ["Java", "Android Studio", "MongoDB", "Realm"],
      link: null,
      github: "https://github.com/vp2305/RideX",
      featured: false,
      accentColor: "#F43F5E",
    },
  ],
  leadership: {
    title: "Beyond the Code",
    roles: [
      {
        id: 1,
        title: "Founder & Event Director",
        organization: "Ontario Gujarati Students Association (OGSA)",
        duration: "Jun. 2021 - Jan. 2024",
        location: "Toronto, ON",
        description: [
          "Founded and led an independent cultural organization hosting 5+ annual events with 700+ attendees.",
          "Grew social media presence resulting in 30% increase in event attendance and community engagement.",
          "Managed a team of 10+ volunteers, coordinating venue selection, budgeting, logistics, and execution.",
        ],
        highlights: ["700+ attendees", "5+ events / year", "10+ person team"],
      },
    ],
  },
  education: {
    degree: "Honours Bachelor of Science, Computer Science",
    school: "Wilfrid Laurier University",
    location: "Waterloo, ON",
    duration: "Sep. 2019 - Dec. 2023",
    achievement: "Dean's List (2020-2021)",
  },
  certifications: [
    {
      name: "Microsoft Certified: Azure Fundamentals",
      issuer: "Microsoft",
      date: "Mar. 2024",
    },
  ],
  contact: {
    title: "Let's Build Something",
    titleAccent: "Together.",
    description:
      "I'm always open to new opportunities, interesting projects, or just a good conversation about technology. Whether you have a role in mind or just want to say hi, my inbox is open.",
    email: "vaibhav.p2305@gmail.com",
    cta: "Say Hello",
  },
  socials: {
    github: "https://github.com/vp2305",
    linkedin: "https://www.linkedin.com/in/vaibhav-patel-3125b6198/",
    instagram: "https://www.instagram.com/vaibhav.p23/",
    email: "mailto:vaibhav.p2305@gmail.com",
  },
  footer: {
    text: "Designed & Built by Vaibhav Patel",
  },
};
